/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/hat4.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lowpolyhat.geometry}
        material={materials['Default OBJ']}
           rotation={[-1, 0.03, -3.09]}
           scale={[10,10,10]}
      />
    </group>
  )
}

useGLTF.preload('/hat4.glb')
